Traceback (most recent call last):
  File "/.autofs/tools/spack/var/spack/environments/default-nlp-x86_64-24072401/.spack-env/._view/wtxwc3mlkmzy7fbaxlum2674jarpitc2/lib/python3.11/shutil.py", line 825, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: '/home/rgg2706/Multimodal-Sentiment-Analysis/Datasets/MVSA-single/data/1.txt' -> '/home/rgg2706/Multimodal-Sentiment-Analysis/Models/MultimodalOpinionAnalysis2/Datasets/MVSA-single/text/1.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rgg2706/Multimodal-Sentiment-Analysis/Models/MultimodalOpinionAnalysis2/run_project.py", line 3, in <module>
    from prepare_datasets import *
  File "/home/rgg2706/Multimodal-Sentiment-Analysis/Models/MultimodalOpinionAnalysis2/prepare_datasets.py", line 93, in <module>
    move_files(
  File "/home/rgg2706/Multimodal-Sentiment-Analysis/Models/MultimodalOpinionAnalysis2/helpers.py", line 76, in move_files
    shutil.move(files_path + '/' + file + extension, destination_path)
  File "/.autofs/tools/spack/var/spack/environments/default-nlp-x86_64-24072401/.spack-env/._view/wtxwc3mlkmzy7fbaxlum2674jarpitc2/lib/python3.11/shutil.py", line 845, in move
    copy_function(src, real_dst)
  File "/.autofs/tools/spack/var/spack/environments/default-nlp-x86_64-24072401/.spack-env/._view/wtxwc3mlkmzy7fbaxlum2674jarpitc2/lib/python3.11/shutil.py", line 436, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/.autofs/tools/spack/var/spack/environments/default-nlp-x86_64-24072401/.spack-env/._view/wtxwc3mlkmzy7fbaxlum2674jarpitc2/lib/python3.11/shutil.py", line 256, in copyfile
    with open(src, 'rb') as fsrc:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/rgg2706/Multimodal-Sentiment-Analysis/Datasets/MVSA-single/data/1.txt'
