/home/rgg2706/Multimodal-Sentiment-Analysis/Models/ESAFN-modified/data_utils.py:55: ResourceWarning: unclosed file <_io.TextIOWrapper name='../util_models/glove.twitter.27B/glove.twitter.27B.100d.txt' mode='r' encoding='utf-8'>
  word_vec = load_word_vec(fname, word2idx=word2idx)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/home/rgg2706/Multimodal-Sentiment-Analysis/Models/ESAFN-modified/data_utils.py:69: ResourceWarning: unclosed file <_io.BufferedWriter name='100_mvsa-mts_embedding_matrix.dat'>
  pickle.dump(embedding_matrix, open(embedding_matrix_file_name, 'wb'))
ResourceWarning: Enable tracemalloc to get the object allocation traceback
Traceback (most recent call last):
  File "/home/rgg2706/Multimodal-Sentiment-Analysis/Models/ESAFN-modified/data_utils.py", line 218, in __read_data__
    image = image_process(image_path, transform)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rgg2706/Multimodal-Sentiment-Analysis/Models/ESAFN-modified/data_utils.py", line 76, in image_process
    image = Image.open(image_path).convert('RGB')
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/.autofs/tools/spack/var/spack/environments/default-ml-x86_64-24071101/.spack-env/view/lib/python3.11/site-packages/PIL/Image.py", line 3218, in open
    fp = builtins.open(filename, "rb")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '../../Datasets/MVSA-Modified/images/2005.jpg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rgg2706/Multimodal-Sentiment-Analysis/Models/ESAFN-modified/train.py", line 386, in <module>
    ins = Instructor(opt)
          ^^^^^^^^^^^^^^^
  File "/home/rgg2706/Multimodal-Sentiment-Analysis/Models/ESAFN-modified/train.py", line 69, in __init__
    absa_dataset = MVSADatasetReader(transform, dataset=opt.dataset, embed_dim=opt.embed_dim, max_seq_len=opt.max_seq_len, \
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rgg2706/Multimodal-Sentiment-Analysis/Models/ESAFN-modified/data_utils.py", line 265, in __init__
    self.train_data = MVSADataset(MVSADatasetReader.__read_data__(fname[dataset]['train'], tokenizer, path_image, transform))
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rgg2706/Multimodal-Sentiment-Analysis/Models/ESAFN-modified/data_utils.py", line 223, in __read_data__
    image = image_process(image_path_fail, transform)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rgg2706/Multimodal-Sentiment-Analysis/Models/ESAFN-modified/data_utils.py", line 76, in image_process
    image = Image.open(image_path).convert('RGB')
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/.autofs/tools/spack/var/spack/environments/default-ml-x86_64-24071101/.spack-env/view/lib/python3.11/site-packages/PIL/Image.py", line 3218, in open
    fp = builtins.open(filename, "rb")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '../../Datasets/MVSA-Modified/images/0default.jpg'
