/.autofs/tools/spack/var/spack/environments/default-nlp-x86_64-24072401/.spack-env/._view/wtxwc3mlkmzy7fbaxlum2674jarpitc2/lib/python3.11/site-packages/jupyter_client/connect.py:20: DeprecationWarning: Jupyter is migrating its paths to use standard platformdirs
given by the platformdirs library.  To remove this warning and
see the appropriate new directories, set the environment variable
`JUPYTER_PLATFORM_DIRS=1` and then run `jupyter --paths`.
The use of platformdirs will be the default in `jupyter_core` v6
  from jupyter_core.paths import jupyter_data_dir, jupyter_runtime_dir, secure_write
Traceback (most recent call last):
  File "/home/rgg2706/Multimodal-Sentiment-Analysis/Models/SIMPLE-F/src/data_utils.py", line 158, in __read_data__
    image = image_process(image_path, transform)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rgg2706/Multimodal-Sentiment-Analysis/Models/SIMPLE-F/src/data_utils.py", line 65, in image_process
    image = Image.open(image_path).convert('RGB')
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/.autofs/tools/spack/var/spack/environments/default-nlp-x86_64-24072401/.spack-env/._view/wtxwc3mlkmzy7fbaxlum2674jarpitc2/lib/python3.11/site-packages/PIL/Image.py", line 3280, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file 'Datasets//MVSA-MTS/images/1337.jpg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rgg2706/Multimodal-Sentiment-Analysis/Models/SIMPLE-F/src/train.py", line 76, in <module>
    ins = Instructor(opt)
          ^^^^^^^^^^^^^^^
  File "/home/rgg2706/Multimodal-Sentiment-Analysis/Models/SIMPLE-F/src/instructor.py", line 61, in __init__
    mvsa_dataset = MVSADatasetReader(transform, dataset=opt.dataset, 
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rgg2706/Multimodal-Sentiment-Analysis/Models/SIMPLE-F/src/data_utils.py", line 211, in __init__
    train_data, train_classes, train_lengths = MVSADatasetReader.__read_data__(train_path, tokenizer, transform, max_seq_len, path_image)
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rgg2706/Multimodal-Sentiment-Analysis/Models/SIMPLE-F/src/data_utils.py", line 160, in __read_data__
    sample_error += 1
    ^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'sample_error' where it is not associated with a value
